### ISSUE TITLE
[ERROR]  docker is logged-in - while logged in

### ISSUE THREAD

**Issue by ronnno** [orbs-network/release-to-staging#5]
docker login fails when docker daemon is not running.

also, /build/docker-images-upload.sh will fail in this case. 

./1-check-setup.sh should check docker is running locally. and possibly prerequisites should install it...

**Comment by talkol** [comment]
IMO docker can't be installed via command line since it's an annoying service that requires admin approval so not sure we should add to prerequisites script, I added a note though

The rest is fixed
